### ISSUE TITLE
Install/running problem- ./MDS.sh: 1: ./MDS.sh: MDS_all: not found

### ISSUE THREAD

**Issue by hanfu-bios** [hiclib/pastis#40]
Hi, 

I used `python setup.py install --user` to install the package on Unix. But I failed to run the examples. It gave me either
`./MDS.sh: 1: ./MDS.sh: MDS_all: not found`
or
`pastis-mds: error: unrecognized arguments: -o -w 8 -r 10000 -k ./files/budding_yeast_structure -i ./wish_distances.txt -d -1 -c 1,2,3,4,5 -y 1`

Any idea why? Do I need to install `MDS_all` and `PM_all` separately from the python package?

Thanks in advance.

Han

**Comment by NelleV** [comment]
Hi @hanfu-bios 
I don't know what I did wrong, but the latest released tag on github does not correspond to the latest release, hence the problem… I'm investigating what happened right now, but in the mean time, can you update with this tarball? https://github.com/hiclib/pastis/archive/v0.3.0.zip
Thanks

**Comment by hanfu-bios** [comment]
Hi,

I downloaded the package v0.3.0 from this link, installed the package via 'python setup.py install —user’. And then when I tried to run the examples, I received the following error:

Traceback (most recent call last):
  File "/usr/local/bin/pastis-mds", line 4, in <module>
    from pastis.algorithms import run_mds
  File "/home/cai.507/.local/lib/python2.7/site-packages/pastis/algorithms.py", line 11, in <module>
    from . import write
ImportError: cannot import name write

Have you seen this before? Do you have any idea how to solve it?

Thanks a lot!

**Comment by NelleV** [comment]
Let me take a couple of hours to investigate what's going on on a fresh install.

**Comment by hanfu-bios** [comment]
Hi Nelle,

Thank you for the efforts for debugging the problems. I tried with this version, but the same error occurred as it did from the last version. 

Traceback (most recent call last):
  File "/usr/local/bin/pastis-mds", line 4, in <module>
    from pastis.algorithms import run_mds
  File "/home/cai.507/.local/lib/python2.7/site-packages/pastis/algorithms.py", line 11, in <module>
    from . import write
ImportError: cannot import name write

Do you have any idea what is going on here?


Thank you a lot!

Best,
Han

**Comment by NelleV** [comment]
After a lot of fighting with packaging, I finally fixed all of the issues. if you reinstall or upgrade via pip, it should work ("pip install --upgrade"). Check that it downloads the 0.3.3 release, which I just released a couple of minutes ago, and it should be ok. It is possible that it takes a couple of hours for the servers to propagate this new release. Let me know if any other problems arise!

**Comment by hanfu-bios** [comment]
Nelle, thank you so much for your efforts! I can run the example right now, but I still have problems running my own data. I have attached my input files here. The error was 

`  File "/Users/hanfu/.local/lib/python3.6/site-packages/pastis/externals/iced/filter.py", line 63, in filter_low_counts
    verbose=verbose)
  File "/Users/hanfu/.local/lib/python3.6/site-packages/pastis/externals/iced/filter.py", line 174, in _filter_low_sum
    X[X_sum < x, :] = np.nan
ValueError: cannot convert float NaN to integer`


Can you please help me by looking into this error?

Thanks a lot!
